package com.floriantrecul.stokkymate.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors
val LightPrimary = Color(0xFF006A60)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFF9EF2E4)
val LightOnPrimaryContainer = Color(0xFF00201C)
val LightSecondary = Color(0xFF4A635F)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFCCE8E2)
val LightOnSecondaryContainer = Color(0xFF05201C)
val LightTertiary = Color(0xFF456179)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFCCE5FF)
val LightOnTertiaryContainer = Color(0xFF001E31)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightSurface = Color(0xFFF4FBF8)
val LightOnSurface = Color(0xFF161D1C)
val LightSurfaceContainer = Color(0xFF3F4947)
val LightOnSurfaceContainer = Color(0xFFE9EFED)
val LightOutline = Color(0xFF6F7977)
val LightOutlineVariant = Color(0xFFBEC9C6)
val LightInverseSurface = Color(0xFF2B3230)
val LightInverseOnSurface = Color(0xFFECF2EF)
val LightInversePrimary = Color(0xFF82D5C8)

// Black Theme Colors
val BlackPrimary = Color(0xFF82D5C8)
val BlackOnPrimary = Color(0xFF003731)
val BlackPrimaryContainer = Color(0xFF005048)
val BlackOnPrimaryContainer = Color(0xFF9EF2E4)
val BlackSecondary = Color(0xFFB1CCC6)
val BlackOnSecondary = Color(0xFF1C3531)
val BlackSecondaryContainer = Color(0xFF334B47)
val BlackOnSecondaryContainer = Color(0xFFCCE8E2)
val BlackTertiary = Color(0xFFADCAE6)
val BlackOnTertiary = Color(0xFF153349)
val BlackTertiaryContainer = Color(0xFF2D4961)
val BlackOnTertiaryContainer = Color(0xFFCCE5FF)
val BlackError = Color(0xFFFFB4AB)
val BlackOnError = Color(0xFF690005)
val BlackErrorContainer = Color(0xFF93000A)
val BlackOnErrorContainer = Color(0xFFFFDAD6)
val BlackSurface = Color(0xFF0E1513)
val BlackOnSurface = Color(0xFFDDE4E1)
val BlackSurfaceContainer = Color(0xFFBEC9C6)
val BlackOnSurfaceContainer = Color(0xFF1A2120)
val BlackOutline = Color(0xFF899390)
val BlackOutlineVariant = Color(0xFF3F4947)
val BlackInverseSurface = Color(0xFFDDE4E1)
val BlackInverseOnSurface = Color(0xFF2B3230)
val BlackInversePrimary = Color(0xFF006A60)